# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcnewspubsub.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14grpcnewspubsub.proto\x12\x0egrpcNewsPubSub\"9\n\x10SubscribeRequest\x12\x15\n\rsubscriber_id\x18\x01 \x01(\t\x12\x0e\n\x06topics\x18\x02 \x03(\t\"T\n\x0bNewsArticle\x12\r\n\x05title\x18\x01 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x03(\t\x12\x0b\n\x03url\x18\x03 \x03(\t\x12\x14\n\x0cpublished_at\x18\x04 \x03(\t2g\n\x0fMsgServUnarySub\x12T\n\x11GetServerResponse\x12 .grpcNewsPubSub.SubscribeRequest\x1a\x1b.grpcNewsPubSub.NewsArticle\"\x00\x32p\n\x18MsgServPubStreamSubUnary\x12T\n\x11GetServerResponse\x12 .grpcNewsPubSub.SubscribeRequest\x1a\x1b.grpcNewsPubSub.NewsArticle0\x01\x62\x06proto3')



_SUBSCRIBEREQUEST = DESCRIPTOR.message_types_by_name['SubscribeRequest']
_NEWSARTICLE = DESCRIPTOR.message_types_by_name['NewsArticle']
SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'grpcnewspubsub_pb2'
  # @@protoc_insertion_point(class_scope:grpcNewsPubSub.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

NewsArticle = _reflection.GeneratedProtocolMessageType('NewsArticle', (_message.Message,), {
  'DESCRIPTOR' : _NEWSARTICLE,
  '__module__' : 'grpcnewspubsub_pb2'
  # @@protoc_insertion_point(class_scope:grpcNewsPubSub.NewsArticle)
  })
_sym_db.RegisterMessage(NewsArticle)

_MSGSERVUNARYSUB = DESCRIPTOR.services_by_name['MsgServUnarySub']
_MSGSERVPUBSTREAMSUBUNARY = DESCRIPTOR.services_by_name['MsgServPubStreamSubUnary']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBSCRIBEREQUEST._serialized_start=40
  _SUBSCRIBEREQUEST._serialized_end=97
  _NEWSARTICLE._serialized_start=99
  _NEWSARTICLE._serialized_end=183
  _MSGSERVUNARYSUB._serialized_start=185
  _MSGSERVUNARYSUB._serialized_end=288
  _MSGSERVPUBSTREAMSUBUNARY._serialized_start=290
  _MSGSERVPUBSTREAMSUBUNARY._serialized_end=402
# @@protoc_insertion_point(module_scope)
